// Code generated by a fictional tool. DO NOT EDIT.

package a

// Gen would be reported if this file were not generated.
type Gen struct {
	X int
}

func (g *Gen) GetX() int {
	return g.X
}

func NewGen() *Gen {
	return &Gen{}
}
